import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTableGpEstruturasSalariais1784911281937 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_ESTRUTURAS_SALARIAIS (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CARGO VARCHAR2(150) NOT NULL,
        CATEGORIA VARCHAR2(100) NOT NULL,
        DESCRICAO VARCHAR2(255),
        ESTADO NUMBER DEFAULT 1 NOT NULL,
        CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_GP_ESTRUTURAS_SALARIAIS PRIMARY KEY (CODIGO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_ESTRUTURAS_SALARIAIS
    `)
  }
}
