import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpAssiduidades1784565426490 implements MigrationInterface {
  name = 'CreateTableGpAssiduidades1784565426490'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "GP_ASSIDUIDADES" ("CODIGO" number GENERATED BY DEFAULT AS IDENTITY, "CODIGO_COLABORADOR" number NOT NULL, "DATA_INICIO" date NOT NULL, "DATA_FIM" date, "HORAS" number(5,2), "SITUACAO" varchar2(20) NOT NULL, "CRIADO_EM" date DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_26589f4d8d11f7901cae621257e" PRIMARY KEY ("CODIGO"))`,
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "GP_ASSIDUIDADES"`)
  }
}
