import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpRubricasSalariais1784912212999 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_RUBRICAS (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        DESCRICAO VARCHAR2(255) NOT NULL,
        TIPO VARCHAR2(20) NOT NULL,
        TIPO_VALOR VARCHAR2(20) NOT NULL,
        VALOR NUMBER(10,2) NOT NULL,
        ESTADO NUMBER DEFAULT 1 NOT NULL,
        CRIADO_EM DATE DEFAULT SYSDATE,
        CONSTRAINT PK_RUBRICAS PRIMARY KEY (CODIGO),
        CONSTRAINT CHK_RUBRICAS_TIPO
          CHECK (TIPO IN ('PROVENTO', 'DESCONTO')),
        CONSTRAINT CHK_RUBRICAS_TIPO_VALOR
          CHECK (TIPO_VALOR IN ('PERCENTUAL', 'FIXO'))
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_RUBRICAS
    `)
  }
}
