import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpLicencas1784832369605 implements MigrationInterface {
  name = 'CreateTableGpLicencas1784832369605'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "GP_LICENCAS" ("CODIGO" number GENERATED BY DEFAULT AS IDENTITY, "CODIGO_COLABORADOR" number NOT NULL, "CODIGO_COLABORADOR_APROVADOR" number, "TIPO" varchar2(20) NOT NULL, "ESTADO" varchar2(20) DEFAULT 'PENDENTE' NOT NULL, "DATA_INICIO" date NOT NULL, "DATA_FIM" date NOT NULL, "CODIGO_DOCUMENTO" number, "OBSERVACAO" varchar2(500), "CRIADO_EM" date DEFAULT CURRENT_TIMESTAMP NOT NULL, "ATUALIZADO_EM" date DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PK_86941237f3d80f90ee6eceeac42" PRIMARY KEY ("CODIGO"))`,
    )
    await queryRunner.query(
      `ALTER TABLE "GP_LICENCAS" ADD CONSTRAINT "FK_5bcfa036324784f8a46df3f4cb0" FOREIGN KEY ("CODIGO_COLABORADOR") REFERENCES "GP_COLABORADORES" ("CODIGO")`,
    )
    await queryRunner.query(
      `ALTER TABLE "GP_LICENCAS" ADD CONSTRAINT "FK_eb6d8e2b5b2266a47e4ac0ef2b4" FOREIGN KEY ("CODIGO_COLABORADOR_APROVADOR") REFERENCES "GP_COLABORADORES" ("CODIGO")`,
    )
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "GP_LICENCAS" DROP CONSTRAINT "FK_eb6d8e2b5b2266a47e4ac0ef2b4"`,
    )
    await queryRunner.query(
      `ALTER TABLE "GP_LICENCAS" DROP CONSTRAINT "FK_5bcfa036324784f8a46df3f4cb0"`,
    )
    await queryRunner.query(`DROP TABLE "GP_LICENCAS"`)
  }
}
