import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpContratos1785515676240 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_CONTRATOS (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        TIPO VARCHAR2(20) NOT NULL,
        ESTADO VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,
        PERMITE_HORA_EXTRA NUMBER DEFAULT 0 NOT NULL,
        HORAS_MENSAIS NUMBER(5,2) NOT NULL,
        CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,

        CONSTRAINT PK_GP_CONTRATOS PRIMARY KEY (CODIGO),

        CONSTRAINT CHK_GP_CONTRATOS_TIPO
          CHECK (TIPO IN ('CONTRATADO', 'HORISTA', 'FIXO')),

        CONSTRAINT CHK_GP_CONTRATOS_ESTADO
          CHECK (ESTADO IN ('ATIVO', 'INATIVO')),

        CONSTRAINT CHK_GP_CONTRATOS_HORA_EXTRA
          CHECK (PERMITE_HORA_EXTRA IN (0, 1))
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_CONTRATOS
    `)
  }
}
