import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpColaboradoresContratos1785515676241 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_COLABORADORES_CONTRATOS (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO_CONTRATO NUMBER NOT NULL,
        CODIGO_COLABORADOR NUMBER NOT NULL,
        ESTADO VARCHAR2(20) DEFAULT 'ATIVO' NOT NULL,
        DATA_INICIO DATE DEFAULT SYSDATE NOT NULL,
        DATA_FIM DATE,

        CONSTRAINT PK_GP_COLAB_CONTRATOS PRIMARY KEY (CODIGO),

        CONSTRAINT CHK_GP_COLAB_CONTRATOS_ESTADO
          CHECK (ESTADO IN ('ATIVO', 'INATIVO')),

        CONSTRAINT FK_GP_COLAB_CONTRATOS_CONTRATO FOREIGN KEY (
          CODIGO_CONTRATO
        ) REFERENCES GP_CONTRATOS (CODIGO),

        CONSTRAINT FK_GP_COLAB_CONTRATOS_COLABORADOR FOREIGN KEY (
          CODIGO_COLABORADOR
        ) REFERENCES GP_COLABORADORES (CODIGO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_COLABORADORES_CONTRATOS
    `)
  }
}
