import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpProcessamentosSalariaisColaboradores1785515676239 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_PROCESSAMENTOS_SALARIAIS_COLABORADORES (
        CODIGO_PROCESSAMENTO_SALARIAL NUMBER NOT NULL,
        CODIGO_COLABORADOR NUMBER NOT NULL,
        CODIGO_ESTRUTURA_SALARIAL NUMBER NOT NULL,
        CODIGO_RUBRICA NUMBER NOT NULL,
        VALOR NUMBER(10,2) NOT NULL,

        CONSTRAINT PK_GP_PROC_SAL_COLAB PRIMARY KEY (
          CODIGO_PROCESSAMENTO_SALARIAL,
          CODIGO_COLABORADOR,
          CODIGO_ESTRUTURA_SALARIAL,
          CODIGO_RUBRICA
        ),

        CONSTRAINT FK_GP_PROC_SAL_COLAB_PROC FOREIGN KEY (
          CODIGO_PROCESSAMENTO_SALARIAL
        ) REFERENCES GP_PROCESSAMENTOS_SALARIAIS (CODIGO),

        CONSTRAINT FK_GP_PROC_SAL_COLAB_COLABORADOR FOREIGN KEY (
          CODIGO_COLABORADOR
        ) REFERENCES GP_COLABORADORES (CODIGO),

        CONSTRAINT FK_GP_PROC_SAL_COLAB_ESTRUTURA FOREIGN KEY (
          CODIGO_ESTRUTURA_SALARIAL
        ) REFERENCES GP_ESTRUTURAS_SALARIAIS (CODIGO),

        CONSTRAINT FK_GP_PROC_SAL_COLAB_RUBRICA FOREIGN KEY (
          CODIGO_RUBRICA
        ) REFERENCES GP_RUBRICAS (CODIGO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_PROCESSAMENTOS_SALARIAIS_COLABORADORES
    `)
  }
}
