import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEUSERCOLABORADOR1788270340780 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_USER_COLABORADOR (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        ID_PESSOA NUMBER NOT NULL,
        ID_USER NUMBER NOT NULL,
        EMAIL VARCHAR2(255) NOT NULL,
        USERNAME VARCHAR2(100) NOT NULL,
        CONSTRAINT FK_USER_COLAB_PESSOA
          FOREIGN KEY (ID_PESSOA)
          REFERENCES PESSOA (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_COLAB_PESSOA
        ON GP_USER_COLABORADOR (ID_PESSOA)
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_COLAB_USER
        ON GP_USER_COLABORADOR (ID_USER)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_USER_COLABORADOR CASCADE CONSTRAINTS
    `)
  }
}
