import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATE_GP_GRAU_ACADEMICO1788173896301 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE  TABLE GP_GRAU_ACADEMICO  (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        DESIGNACAO VARCHAR2(100) NOT NULL,

        SIGLA VARCHAR2(30),

        ORDEM NUMBER NOT NULL,

        ESTADO NUMBER(1,0)
          DEFAULT 1
          NOT NULL,

        CRIADO_EM DATE
          DEFAULT SYSDATE
          NOT NULL,

        CONSTRAINT CK_GP_GRAU_ACAD_ESTADO
          CHECK (ESTADO IN (0,1))
      )
    `)

    await queryRunner.query(`
      INSERT INTO GP_GRAU_ACADEMICO
        (DESIGNACAO, SIGLA, ORDEM)
      VALUES
        ('Licenciado', 'LIC', 1)
    `)

    await queryRunner.query(`
      INSERT INTO GP_GRAU_ACADEMICO
        (DESIGNACAO, SIGLA, ORDEM)
      VALUES
        ('Mestre', 'MST', 2)
    `)

    await queryRunner.query(`
      INSERT INTO GP_GRAU_ACADEMICO
        (DESIGNACAO, SIGLA, ORDEM)
      VALUES
        ('Doutor/a', 'DTR', 3)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_GRAU_ACADEMICO CASCADE CONSTRAINTS
    `)
  }
}
