import { MigrationInterface, QueryRunner } from 'typeorm'

export class GpInformationAdicionalDocente1788359872452
  implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_INFORMACAO_ADICIONAL_DOCENTE (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        
    
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_INFORMACAO_ADICIONAL_DOCENTE
    `)
  }
}
