import { MigrationInterface, QueryRunner } from 'typeorm'

export class GpCandidaturasHistorico1788359786886 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_CANDIDATURAS_HISTORICO (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO_CANDIDATURA NUMBER NOT NULL,
        ESTADO_ANTERIOR VARCHAR2(20),
        ESTADO_NOVO VARCHAR2(20) NOT NULL,
        OBSERVACAO VARCHAR2(500),
        CODIGO_UTILIZADOR NUMBER,
        CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,

        CONSTRAINT PK_GP_CANDIDATURAS_HISTORICO PRIMARY KEY (CODIGO),

        CONSTRAINT FK_GP_CAND_HIST_CANDIDATURA
          FOREIGN KEY (CODIGO_CANDIDATURA) REFERENCES GP_CANDIDATURAS (CODIGO),
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_CANDIDATURAS_HISTORICO
    `)
  }
}
