import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEUSERCOLABORADOR1788270340780 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_USER_COLABORADOR (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_USER_COLABORADOR PRIMARY KEY,
        CODIGO_PESSOA NUMBER NOT NULL,
        EMAIL VARCHAR2(255) NOT NULL,
        USERNAME VARCHAR2(100) NOT NULL,
        CONSTRAINT UQ_GP_USER_COLAB_EMAIL UNIQUE (EMAIL),
        CONSTRAINT UQ_GP_USER_COLAB_USERNAME UNIQUE (USERNAME),
        CONSTRAINT FK_USER_COLAB_PESSOA
          FOREIGN KEY (CODIGO_PESSOA)
          REFERENCES GP_PESSOA (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_COLAB_PESSOA
        ON GP_USER_COLABORADOR (CODIGO_PESSOA)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_USER_COLABORADOR CASCADE CONSTRAINTS
    `)
  }
}
