import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEPESSOA1788270193039 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_PESSOA (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_PESSOA PRIMARY KEY,
        NOME VARCHAR2(255) NOT NULL,
        BI VARCHAR2(50),
        NIF VARCHAR2(50),
        TELEFONE VARCHAR2(30),
        TELEFONE_ALTERNATIVO VARCHAR2(30),
        NOME_MAE VARCHAR2(255),
        NOME_PAI VARCHAR2(255),
        CODIGO_NACIONALIDADE NUMBER,
        CODIGO_ESTADO_CIVIL NUMBER,
        CODIGO_GENERO NUMBER,
        DATA_NASCIMENTO DATE,
        DATA_DE_EMISSAO_DOCUMENTO DATE,
        DATA_DE_EXPIRACAO_DOCUMENTO DATE,
        STATUS NUMBER(1) DEFAULT 1 NOT NULL,
        CONSTRAINT CK_GP_PESSOA_STATUS CHECK (STATUS IN (0, 1))
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_PESSOA CASCADE CONSTRAINTS
    `)
  }
}
