import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpEstadoAgendamentoEntrevista1788449156188 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_ESTADO_AGENDAMENTO_ENTREVISTA (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_ESTADO_AGENDAMENTO_ENTREVISTA PRIMARY KEY,
        DESIGNACAO VARCHAR2(100) NOT NULL,
        CONSTRAINT UQ_GP_ESTADO_AGEND_ENTR_DESIGNACAO UNIQUE (DESIGNACAO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_ESTADO_AGENDAMENTO_ENTREVISTA CASCADE CONSTRAINTS
    `)
  }
}
