import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEGPEXPPROFISSIONAL1788181356221 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_EXP_PROFISSIONAL (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        CANDIDATO_ID NUMBER NOT NULL,

        INSTITUICAO VARCHAR2(255),

        AREA VARCHAR2(255),

        FUNCAO VARCHAR2(255),

        CARGO VARCHAR2(255),

        ANO_INICIO NUMBER,

        ANO_FIM NUMBER,

        CRIADO_EM DATE
          DEFAULT SYSDATE
          NOT NULL,

        CONSTRAINT FK_GP_EXP_PROF_CANDIDATO
          FOREIGN KEY (CANDIDATO_ID)
          REFERENCES GP_CANDIDATOS (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_EXP_PROF_CANDIDATO
        ON GP_EXP_PROFISSIONAL (CANDIDATO_ID)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_EXP_PROFISSIONAL CASCADE CONSTRAINTS
    `)
  }
}
