import { MigrationInterface, QueryRunner } from 'typeorm'

export class GpCandidaturasHistorico1788359786886 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_CANDIDATURAS_HISTORICO (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO_CANDIDATURA NUMBER NOT NULL,
        ACAO VARCHAR2(50) NOT NULL,
        ESTADO_ANTERIOR NUMBER,
        ESTADO_NOVO NUMBER,
        RESPONSAVEL_ID NUMBER,
        OBSERVACAO VARCHAR2(2000),
        DATA DATE DEFAULT SYSDATE NOT NULL,
        CONSTRAINT PK_GP_CANDIDATURAS_HISTORICO PRIMARY KEY (CODIGO),
        CONSTRAINT FK_GP_CAND_HIST_CANDIDATURA FOREIGN KEY (CODIGO_CANDIDATURA)
          REFERENCES GP_CANDIDATURAS (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IX_GP_CAND_HIST_CANDIDATURA
        ON GP_CANDIDATURAS_HISTORICO (CODIGO_CANDIDATURA)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_CANDIDATURAS_HISTORICO
    `)
  }
}
