import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEGPFORMACAOACADEMICA1788181242514 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_FORMACAO_ACADEMICA (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        CANDIDATO_ID NUMBER NOT NULL,

        GRAU_ID NUMBER,

        AREA_FORMACAO VARCHAR2(500),

        INSTITUICAO VARCHAR2(255),

        ANO_CONCLUSAO NUMBER,

        MEDIA_FINAL NUMBER(5,2),

        CRIADO_EM DATE
          DEFAULT SYSDATE
          NOT NULL,

        CONSTRAINT FK_GP_FORM_ACAD_CANDIDATO
          FOREIGN KEY (CANDIDATO_ID)
          REFERENCES GP_CANDIDATOS (CODIGO),

        CONSTRAINT FK_GP_FORM_ACAD_GRAU
          FOREIGN KEY (GRAU_ID)
          REFERENCES GP_GRAU_ACADEMICO (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_FORM_ACAD_CANDIDATO
        ON GP_FORMACAO_ACADEMICA (CANDIDATO_ID)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_FORMACAO_ACADEMICA CASCADE CONSTRAINTS
    `)
  }
}
