import { MigrationInterface, QueryRunner } from 'typeorm'

export class GpCandidaturas1788359750010 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_CANDIDATURAS (
        CODIGO NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        CODIGO_VAGA NUMBER,
        CODIGO_CANDIDATO NUMBER,
        ESTADO NUMBER,
        CRIADO_EM DATE DEFAULT SYSDATE NOT NULL,
        ATUALIZADO_EM DATE DEFAULT SYSDATE,
        CONSTRAINT PK_GP_CANDIDATURAS PRIMARY KEY (CODIGO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_CANDIDATURAS
    `)
  }
}