import { MigrationInterface, QueryRunner } from 'typeorm'

export class GpInformationAdicionalDocente1788359872452
  implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_INFORMACAO_ADICIONAL_DOCENTE (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        CODIGO_CANDIDATO NUMBER,

        N_MECANOGRAFICO VARCHAR2(255),

        ESCALAO NUMBER,

        CATEGORIA_DOCENTE NUMBER,
        
        FACULDADE NUMBER,

        COD_CONTRATO NUMBER,

        TOTAL_ANO_EXPERIENCIA NUMBER,

        DATA_INICIO_DOCENCIA DATE,

        APRECIACAO VARCHAR2(300),

        CRIADO_EM DATE
          DEFAULT SYSDATE
          NOT NULL,

        ATUALIZADO_EM DATE
          DEFAULT SYSDATE,

       
    `)


  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_INFORMACAO_ADICIONAL_DOCENTE CASCADE CONSTRAINTS
    `)
  }
}
