import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpAgendamentoEntrevistaEntrevistador1788449158666 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_AGENDAMENTO_ENTREVISTA_ENTREVISTADOR (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_AGEND_ENTR_ENTREVISTADOR PRIMARY KEY,
        CODIGO_AGENDAMENTO_ENTREVISTA NUMBER NOT NULL,
        CODIGO_USER NUMBER NOT NULL,
        CONSTRAINT FK_GP_AEE_AGENDAMENTO
          FOREIGN KEY (CODIGO_AGENDAMENTO_ENTREVISTA)
          REFERENCES GP_AGENDAMENTO_ENTREVISTA (CODIGO)
          ON DELETE CASCADE,
        CONSTRAINT FK_GP_AEE_USER
          FOREIGN KEY (CODIGO_USER)
          REFERENCES GP_USUARIOS (CODIGO),
        CONSTRAINT UQ_GP_AEE_AGENDAMENTO_USER
          UNIQUE (CODIGO_AGENDAMENTO_ENTREVISTA, CODIGO_USER)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_AGENDAMENTO_ENTREVISTA_ENTREVISTADOR CASCADE CONSTRAINTS
    `)
  }
}
