import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEGPEXPDOCENTE1788181310324 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_EXP_DOCENTE (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,

        CANDIDATO_ID NUMBER NOT NULL,

        TITULO VARCHAR2(255),

        CURSO VARCHAR2(255),

        INSTITUICAO VARCHAR2(255),

        DISCIPLINA VARCHAR2(255),

        ANO_INICIO NUMBER,

        ANO_FIM NUMBER,

        CRIADO_EM DATE
          DEFAULT SYSDATE
          NOT NULL,

        CONSTRAINT FK_GP_EXP_DOC_CANDIDATO
          FOREIGN KEY (CANDIDATO_ID)
          REFERENCES GP_CANDIDATOS (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_EXP_DOC_CANDIDATO
        ON GP_EXP_DOCENTE (CANDIDATO_ID)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_EXP_DOCENTE CASCADE CONSTRAINTS
    `)
  }
}
