import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEUSERADMIN1788270449287 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_USER_ADMIN (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,
        ID_PESSOA NUMBER NOT NULL,
        ID_USER_ADMIN NUMBER NOT NULL,
        EMAIL VARCHAR2(255) NOT NULL,
        USERNAME VARCHAR2(100) NOT NULL,
        CONSTRAINT FK_USER_ADMIN_PESSOA
          FOREIGN KEY (ID_PESSOA)
          REFERENCES PESSOA (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_ADMIN_PESSOA
        ON GP_USER_ADMIN (ID_PESSOA)
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_ADMIN_USER
        ON GP_USER_ADMIN (ID_USER_ADMIN)
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_ADMIN_EXTERNAL
        ON GP_USER_ADMIN (EXTERNAL_ID)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_USER_ADMIN CASCADE CONSTRAINTS
    `)
  }
}
