import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEPESSOA1788270193039 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_PESSOA (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          PRIMARY KEY,
        NOME VARCHAR2(255) NOT NULL,
        BI VARCHAR2(50),
        NIF VARCHAR2(50),
        TELEFONE VARCHAR2(30),
        TELEFONE_ALTERNATIVO VARCHAR2(30),
        STATUS VARCHAR2(30),
        NACIONALIDADE VARCHAR2(100)
        NACIONALIDADE_ID NUMBER,
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE PESSOA CASCADE CONSTRAINTS
    `)
  }
}
