import { MigrationInterface, QueryRunner } from 'typeorm'

export class CreateTableGpModalidade1788449149941 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_MODALIDADE (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_MODALIDADE PRIMARY KEY,
        DESIGNACAO VARCHAR2(100) NOT NULL,
        CONSTRAINT UQ_GP_MODALIDADE_DESIGNACAO UNIQUE (DESIGNACAO)
      )
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_MODALIDADE CASCADE CONSTRAINTS
    `)
  }
}
