import { MigrationInterface, QueryRunner } from 'typeorm'

export class CREATEUSERADMIN1788270449287 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE GP_USER_ADMIN (
        CODIGO NUMBER
          GENERATED BY DEFAULT ON NULL AS IDENTITY
          CONSTRAINT PK_GP_USER_ADMIN PRIMARY KEY,
        CODIGO_PESSOA NUMBER NOT NULL,
        EMAIL VARCHAR2(255) NOT NULL,
        USERNAME VARCHAR2(100) NOT NULL,
        CONSTRAINT UQ_GP_USER_ADMIN_EMAIL UNIQUE (EMAIL),
        CONSTRAINT UQ_GP_USER_ADMIN_USERNAME UNIQUE (USERNAME),
        CONSTRAINT FK_USER_ADMIN_PESSOA
          FOREIGN KEY (CODIGO_PESSOA)
          REFERENCES GP_PESSOA (CODIGO)
      )
    `)

    await queryRunner.query(`
      CREATE INDEX IDX_GP_USER_ADMIN_PESSOA
        ON GP_USER_ADMIN (CODIGO_PESSOA)
    `)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE GP_USER_ADMIN CASCADE CONSTRAINTS
    `)
  }
}
